# Generated by Django 5.0.6 on 2024-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
